services:
  app:
    build: .
    container_name: parking_bot_app
    restart: always
    volumes:
      - ./logs:/opt/parking-bot/logs
      - ./media:/opt/parking-bot/media
      - ./tokens:/opt/parking-bot/tokens
    depends_on:
      - mongodb
    networks:
      - parking-network

  mongodb:
    image: mongo:4.4
    container_name: parking_bot_mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - parking-network

networks:
  parking-network:
    driver: bridge

volumes:
  mongodb_data:

